str=input('enter your string:')
a= int(input('enter the place number that you want to start:'))
b= int(input('enter the place number that you want to end:'))
c= int(input('enter the place number that you want to start:'))
d= int(input('enter the place number that you want to end:'))
print(str[a:b+1] +" " + str[c:d+1])
